language: cpp

sudo: required

services:
    - docker

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install --yes qtbase5-dev qtdeclarative5-dev
    - sudo apt-get install --yes qt5-default qttools5-dev-tools libnl-route-3-dev
    - qmake -version

script:
    - qmake cangaroo.pro
    - make

git:
    depth: 3
